name: Run Rfam SQL Query

on:
  push:
    paths:
      - 'query.sql'   # запускается ТОЛЬКО при изменении этого файла

jobs:
  run-query:
    runs-on: ubuntu-latest # Установка ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3 #Клонирование репы

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client #Установка MySQL

      - name: Run SQL query #Подключение к базе и запуск запроса.
        run: |
          mysql \
            --user=rfamro \
            --host=mysql-rfam-public.ebi.ac.uk \
            --port=4497 \
            --database=Rfam \
            < query.sql